// buildnumber.h
//
// Auto-generated by cmake/update_build_version.cmake
// DO NOT include this file from headers - only include it in the .cpp files
// that actually display the version string. This keeps rebuilds minimal.

#ifndef _____VSCP_BUILDNUMBER_h_____
#define _____VSCP_BUILDNUMBER_h_____

#define VSCPWORKS_BUILD_VERSION     35   

#define VSCPWORKS_DISPLAY_VERSION   "0.0.3-35"

#endif
