name: Linux Build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:  
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]

    steps:

    # https://github.com/actions/checkout  
    - uses: actions/checkout@v2

    - name: Checkout vscp repo
      uses: actions/checkout@v2
      with:
        repository: grodansparadis/vscp
        path: vscp
        ref: development

    - name: Checkout eclipse paho repo
      uses: actions/checkout@v2
      with:
        repository: eclipse/paho.mqtt.c
        path: paho

    - name: Update before installing packages
      run: sudo apt-get update

    - name: Install libmosquitto-dev manually
      run: sudo apt-get install libmosquitto-dev
    
    - name: Install libexpat-dev manually
      run: sudo apt-get install libexpat-dev

    - name: Install libssl-dev manually
      run: sudo apt-get install libssl-dev

    - name: Install paho manually
      run: cd paho && mkdir build && cd build && sudo cmake -DPAHO_WITH_SSL=true .. && sudo make install
       
    - name: Install qt5 components manually
      run: sudo apt install qttools5-dev qt5-default qtdeclarative5-dev libqt5charts5-dev 

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9 
    
    - name: Create Build Environment
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DVSCP_PATH=vscp/

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        make -j$(nproc)
        make install DESTDIR=AppDir

