name: Linux Build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:  
      matrix:
        os: [ubuntu-latest]

    steps:

      # https://github.com/marketplace/actions/install-qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.2.*
        dir: ${{ github.workspace }}/qt/

      # https://github.com/actions/checkout  
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout vscp repo
      uses: actions/checkout@v4
      with:
        repository: grodansparadis/vscp
        path: ${{github.workspace}}/vscp
        ref: development  
        submodules: recursive

    - name: Checkout eclipse paho repo
      uses: actions/checkout@v4
      with:
        repository: eclipse/paho.mqtt.c
        path: paho

    - name: Update before installing packages
      run: sudo apt-get update

    - name: Install libmosquitto-dev manually
      run: sudo apt-get install libmosquitto-dev
    
    - name: Install libexpat-dev manually
      run: sudo apt-get install libexpat-dev

    - name: Install libssl-dev manually
      run: sudo apt-get install libssl-dev

    - name: Install libcurl4-openssl-dev manually 
      run: sudo apt install libcurl4-openssl-dev  

    - name: Install libwebsockets-dev 
      run: sudo apt install libwebsockets-dev   

    - name: Install paho manually
      run: cd paho && mkdir build && cd build && sudo cmake -DPAHO_WITH_SSL=true .. && sudo make install
       
    - name: Install qt5 components manually
      run: sudo apt install qttools5-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qtdeclarative5-dev libqt5charts5-dev libqt5serialbus5-dev libqt5serialport5-dev

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2 
    
    - name: Create Build Environment
      run: |
        mkdir build && cd build
        cmake  -DCMAKE_INSTALL_PREFIX=/usr -DVSCP_ROOT=${{github.workspace}}/vscp/ ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        make -j$(nproc)
        make install DESTDIR=AppDir

